---
- name: Create celery pid dir
  file:
    path: /var/run/celery
    state: directory
    owner: falco

- name: Install celery service
  template:
    src: celery.service.j2
    dest: /etc/systemd/system/celery.service
  notify: Restart celery
