- name: Install system requirements
  apt:
    name: "{{ system_packages }}"
    update_cache: yes

- name: Upgrade pip
  pip:
    name: pip
    state: latest

- name: Install pip requirements
  pip:
    name: "{{ pip_packages }}"
